version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_PASSWORD=my_password
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb_data:/bitnami'

  myapp:
    tty: true
    image: 'bitnami/laravel:latest'
    labels:
      kompose.service.type: nodeport
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
    #command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=3000", "& npm", "run", "hot"]
  # phpmyadmin:
    # image: 'bitnami/phpmyadmin:latest'
    # ports:
      # - '8080:80'
    # depends_on:
      # - mariadb

volumes:
  mariadb_data:
    driver: local
